//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitie : DbContext
    {
        public Entitie()
            : base("name=Entitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<reorder> reorder { get; set; }
        public virtual DbSet<retailstore> retailstore { get; set; }
        public virtual DbSet<sale_order> sale_order { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<workman> workman { get; set; }
    }
}
