//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int AccountID { get; set; }
        public string Acc_Username { get; set; }
        public string Acc_Password { get; set; }
        public string Acc_PhoneNumber { get; set; }
        public string Acc_Address { get; set; }
        public Nullable<System.DateTime> Acc_DOB { get; set; }
        public Nullable<int> Acc_status { get; set; }
        public Nullable<int> Acc_AccRight { get; set; }
        public string Salary { get; set; }
        public string DepartmentName { get; set; }
    }
}
