//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public string ordNum { get; set; }
        public string ordTime { get; set; }
        public string price { get; set; }
        public string method { get; set; }
        public string dilyStatus { get; set; }
        public string deliver { get; set; }
        public string payStatus { get; set; }
    }
}
